### ISSUE TITLE
When a user do *help an error occur

### ISSUE THREAD

**Issue by RisedSky** [RisedSky/discordPandaJS#44]
(node:4) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'voiceChannel' of null
2018-04-13T16:15:25.378759+00:00 app[worker.1]:     at Client.bot.on (/app/discordPanda.js:370:18)
2018-04-13T16:15:25.378761+00:00 app[worker.1]:     at emitOne (events.js:116:13)
2018-04-13T16:15:25.378762+00:00 app[worker.1]:     at Client.emit (events.js:211:7)
2018-04-13T16:15:25.378764+00:00 app[worker.1]:     at MessageCreateHandler.handle (/app/node_modules/discord.js/src/client/websocket/packets/handlers/MessageCreate.js:9:34)
2018-04-13T16:15:25.378766+00:00 app[worker.1]:     at WebSocketPacketManager.handle (/app/node_modules/discord.js/src/client/websocket/packets/WebSocketPacketManager.js:103:65)
2018-04-13T16:15:25.378767+00:00 app[worker.1]:     at WebSocketConnection.onPacket (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:330:35)
2018-04-13T16:15:25.378768+00:00 app[worker.1]:     at WebSocketConnection.onMessage (/app/node_modules/discord.js/src/client/websocket/WebSocketConnection.js:293:17)
2018-04-13T16:15:25.378770+00:00 app[worker.1]:     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
2018-04-13T16:15:25.378771+00:00 app[worker.1]:     at emitOne (events.js:116:13)
2018-04-13T16:15:25.378772+00:00 app[worker.1]:     at WebSocket.emit (events.js:211:7)
2018-04-13T16:15:25.378784+00:00 app[worker.1]: (node:4) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1757)

**Comment by RisedSky** [comment]
The problem occur in a different way, in the other servers it seems that it don't occur but on some it does, i don't know why, need to work on it and investigate it.

**Comment by RisedSky** [comment]
Seems to not occur anymore, i close this issue.
